apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-vllm-may26 
  janus-idp.io/tekton: rag-vllm-may26
  backstage.io/kubernetes-id: rag-vllm-may26
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-vllm-may26
resources: 
- application-dev.yaml