apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-vllm-may26
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/rag-vllm-may26:ec440f8329a9835952f3888066b5c898db2f433b@sha256:a3b34f228eb9d7e135e6f2a2273e1c68c56f624bbd558f7ae2df4b83f594e818 # use pre-built to bootstrap 
          name: app-inference
