apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag-vllm-may26
  janus-idp.io/tekton: rag-vllm-may26
  backstage.io/kubernetes-id: rag-vllm-may26
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-vllm-may26
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
